  { FIT_FILE_DEVICE, "device", "Read only, single file. Must be in root directory." },
  { FIT_FILE_SETTINGS, "settings", "Read/write, single file. Directory=Settings" },
  { FIT_FILE_SPORT, "sport", "Read/write, multiple files, file number = sport type. Directory=Sports" },
  { FIT_FILE_ACTIVITY, "activity", "Read/erase, multiple files. Directory=Activities" },
  { FIT_FILE_WORKOUT, "workout", "Read/write/erase, multiple files. Directory=Workouts" },
  { FIT_FILE_COURSE, "course", "Read/write/erase, multiple files. Directory=Courses" },
  { FIT_FILE_SCHEDULES, "schedules", "Read/write, single file. Directory=Schedules" },
  { FIT_FILE_WEIGHT, "weight", "Read only, single file. Circular buffer. All message definitions at start of file. Directory=Weight" },
  { FIT_FILE_TOTALS, "totals", "Read only, single file. Directory=Totals" },
  { FIT_FILE_GOALS, "goals", "Read/write, single file. Directory=Goals" },
  { FIT_FILE_BLOOD_PRESSURE, "blood_pressure", "Read only. Directory=Blood Pressure" },
  { FIT_FILE_MONITORING_A, "monitoring_a", "Read only. Directory=Monitoring. File number=sub type." },
  { FIT_FILE_ACTIVITY_SUMMARY, "activity_summary", "Read/erase, multiple files. Directory=Activities" },
  { FIT_FILE_MONITORING_DAILY, "monitoring_daily", "" },
  { FIT_FILE_MONITORING_B, "monitoring_b", "Read only. Directory=Monitoring. File number=identifier" },
  { FIT_FILE_SEGMENT, "segment", "Read/write/erase. Multiple Files.  Directory=Segments" },
  { FIT_FILE_SEGMENT_LIST, "segment_list", "Read/write/erase. Single File.  Directory=Segments" },
  { FIT_FILE_EXD_CONFIGURATION, "exd_configuration", "Read/write/erase. Single File. Directory=Settings" },
  { FIT_FILE_MFG_RANGE_7, "mfg_range7", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_8, "mfg_range8", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_9, "mfg_range9", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_A, "mfg_rangeA", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_B, "mfg_rangeB", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_C, "mfg_rangeC", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_D, "mfg_rangeD", "Reserved for manufacturer specific file types" },
  { FIT_FILE_MFG_RANGE_E, "mfg_rangeE", "Reserved for manufacturer specific file types" },
